### ISSUE TITLE
more detail on rejection of nightwatch

### ISSUE THREAD

**Issue by grawk** [dowjones/fiveby#16]
I'm curious about the specific issues that kept you from considering nightwatch in favor of building your own library? I also built a selenium abstraction and get asked a lot about this. For me, the main thing that steered me away from nightwatch was it proscribed a test runner and assertion library. I wanted to have the freedom to choose between mocha, jasmine, or cucumber (just to name some). Also, based on my company's requirements, the parallelization mechanism wasn't flexible enough.

Still, nightwatch is attractive to managers and others who see the nice website, extensive API, and large team of contributors... Curious about your opinion. Thanks!

**Comment by scott2449** [comment]
1) The api is way different from webdriverjs. I really dislike libraries that try to abstract it or use a non-selenium project wire protocol implementation like http://webdriver.io/. Selenium has a hard enough time not breaking down completely with every new browser and all it's moving parts (it's amazing don't get me wrong). The last thing it needs is another layer / abstraction. Not to mention that abstraction means more debugging for me when devs need help. This also means alot of code whereas the workhorse of fiveby is like 150 lines of code.

2) I honestly didn't know about until half of the teams had 100s of tests in fiveby. We all have pretty crappy SEO (partial because the terminology is a b****!) I didn't know about nemo until node summit =/

3) We have teams using nightwatch as well (in another division of the company) and they are evaluating fiveby in real usage side by side so I might be able to give you more info in a few months

4) fiveby is almost more about the documentation and practices than the code. It is an answer to all the questions I got on a daily basis: how should I do X with my tests?

**Comment by scott2449** [comment]
speaking of that here is what I do know about, aware of others? I feel like there are probably double :grinning: 

nemo 
webdriver.io 
wd-parallels 
nightwatch 
protractor 
theintern 
casperjs
busterjs
karma

(of course there are simpler things like raw phantom but that would be horrible)

**Comment by grawk** [comment]
That list is what I'm aware of. Like you said, may be others as well.

I'm currently evaluating features for the nemo v1.0 release. Talking with our internal users. The "did you look at X" question comes up. My answer was rather simple as I mentioned earlier. I agree with your additional sentiments about recreating or overly abstracting the actual webdriver commands.

I'm trying to determine the best way to get your feedback as well. Maybe I can just set up a conference call in the next couple weeks and give you a high level overview of what I _think_ 1.0 should look like.

**Comment by grawk** [comment]
And as always, thanks for your time!
